"""Projection, positional embedding, and camera-trajectory helpers."""

import logging

import torch
from einops import einsum, rearrange
from jaxtyping import Float, Int64
from torch import Tensor


def homogenize_points(
    points: Float[Tensor, "*batch dim"],
) -> Float[Tensor, "*batch dim+1"]:
    """Convert batched points (xyz) to (xyz1)."""
    return torch.cat([points, torch.ones_like(points[..., :1])], dim=-1)


def unproject(
    coordinates: Float[Tensor, "*#batch dim"],
    z: Float[Tensor, "*#batch"],
    intrinsics: Float[Tensor, "*#batch dim+1 dim+1"],
) -> Float[Tensor, "*batch dim+1"]:
    """Unproject 2D camera coordinates with the given Z values."""

    coordinates = homogenize_points(coordinates)
    ray_directions = einsum(intrinsics.inverse(), coordinates, "... i j, ... j -> ... i")

    return ray_directions * z[..., None]


def get_local_rays(
    coordinates: Float[Tensor, "*#batch dim"],
    intrinsics: Float[Tensor, "*#batch dim+1 dim+1"],
) -> Float[Tensor, "*batch dim+1"]:
    directions = unproject(
        coordinates,
        torch.ones_like(coordinates[..., 0]),
        intrinsics,
    )
    directions = directions / directions.norm(dim=-1, keepdim=True)
    return directions


def sample_image_grid(
    shape: tuple[int, ...],
    device: torch.device = torch.device("cpu"),
) -> tuple[
    Float[Tensor, "*shape dim"],
    Int64[Tensor, "*shape dim"],
]:
    """Get normalized (range 0 to 1) coordinates and integer indices for an image."""

    # Each entry is a pixel-wise integer coordinate. In the 2D case, each entry is a
    # (row, col) coordinate.
    indices = [torch.arange(length, device=device) for length in shape]
    stacked_indices = torch.stack(torch.meshgrid(*indices, indexing="ij"), dim=-1)

    # Each entry is a floating-point coordinate in the range (0, 1). In the 2D case,
    # each entry is an (x, y) coordinate.
    coordinates = [(idx + 0.5) / length for idx, length in zip(indices, shape)]
    coordinates = reversed(coordinates)
    coordinates = torch.stack(torch.meshgrid(*coordinates, indexing="xy"), dim=-1)

    return coordinates, stacked_indices


def rsh_cart_4(xyz: torch.Tensor):
    """Computes all real spherical harmonics up to degree 4.

    This is an autogenerated method. See
    https://github.com/cheind/torch-spherical-harmonics
    for more information.

    Params:
        xyz: (N,...,3) tensor of points on the unit sphere

    Returns:
        rsh: (N,...,25) real spherical harmonics
            projections of input. Ynm is found at index
            `n*(n+1) + m`, with `0 <= n <= degree` and
            `-n <= m <= n`.
    """
    x = xyz[..., 0]
    y = xyz[..., 1]
    z = xyz[..., 2]

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z
    x4 = x2**2
    y4 = y2**2

    return torch.stack(
        [
            xyz.new_tensor(0.282094791773878).expand(xyz.shape[:-1]),
            -0.48860251190292 * y,
            0.48860251190292 * z,
            -0.48860251190292 * x,
            1.09254843059208 * xy,
            -1.09254843059208 * yz,
            0.94617469575756 * z2 - 0.31539156525252,
            -1.09254843059208 * xz,
            0.54627421529604 * x2 - 0.54627421529604 * y2,
            -0.590043589926644 * y * (3.0 * x2 - y2),
            2.89061144264055 * xy * z,
            0.304697199642977 * y * (1.5 - 7.5 * z2),
            1.24392110863372 * z * (1.5 * z2 - 0.5) - 0.497568443453487 * z,
            0.304697199642977 * x * (1.5 - 7.5 * z2),
            1.44530572132028 * z * (x2 - y2),
            -0.590043589926644 * x * (x2 - 3.0 * y2),
            2.5033429417967 * xy * (x2 - y2),
            -1.77013076977993 * yz * (3.0 * x2 - y2),
            0.126156626101008 * xy * (52.5 * z2 - 7.5),
            0.267618617422916 * y * (2.33333333333333 * z * (1.5 - 7.5 * z2) + 4.0 * z),
            1.48099765681286 * z * (1.66666666666667 * z * (1.5 * z2 - 0.5) - 0.666666666666667 * z)
            - 0.952069922236839 * z2
            + 0.317356640745613,
            0.267618617422916 * x * (2.33333333333333 * z * (1.5 - 7.5 * z2) + 4.0 * z),
            0.063078313050504 * (x2 - y2) * (52.5 * z2 - 7.5),
            -1.77013076977993 * xz * (x2 - 3.0 * y2),
            -3.75501441269506 * x2 * y2 + 0.625835735449176 * x4 + 0.625835735449176 * y4,
        ],
        -1,
    )


def get_intrinsic_embedding_new(intrinsics, images, degree=0, downsample=1, merge_hw=False):
    """Build a pixelwise embedding from normalized camera ray directions."""
    assert degree in [0, 4], f"unsupported intrinsics embedding degree: {degree}"

    bv, _, h, w = images.shape
    device = images.device
    tgt_h, tgt_w = h // downsample, w // downsample
    xy_ray, _ = sample_image_grid((tgt_h, tgt_w), device)
    xy_ray = xy_ray[None, ...].expand(bv, -1, -1, -1)
    directions = get_local_rays(
        xy_ray,
        rearrange(intrinsics, "b v i j -> (b v) () () i j"),
    )

    if degree == 4:
        directions = rsh_cart_4(directions)

    if merge_hw:
        directions = rearrange(directions, "bv h w d -> bv (h w) d")
    else:
        directions = rearrange(directions, "bv h w d -> bv d h w")

    return directions


@torch.amp.autocast("cuda", enabled=False)
def calculate_camera_poses_scale(
    camera_poses: Float[Tensor, "b v 4 4"],
) -> Float[Tensor, " b"]:
    """Return the maximum pairwise camera-center distance for each batch item."""
    assert camera_poses.size(1) > 1

    centers = camera_poses[:, :, :3, 3].float()
    scales = torch.cdist(centers, centers).amax(dim=(-2, -1))

    if (scales == 0).any():
        logging.getLogger(__name__).error(
            "calculate_camera_poses_scale is 0.0; replacing with 1.0; camera_poses: %s",
            camera_poses,
        )
        scales = torch.where(scales == 0, torch.ones_like(scales), scales)

    return scales


def se3_inverse(T: Tensor) -> Tensor:
    """Computes the inverse of a batch of SE(3) matrices."""
    R = T[..., :3, :3]
    t = T[..., :3, 3].unsqueeze(-1)
    R_inv = R.transpose(-2, -1)
    t_inv = -torch.matmul(R_inv, t)
    T_inv = torch.cat(
        [
            torch.cat([R_inv, t_inv], dim=-1),
            torch.tensor([0, 0, 0, 1], device=T.device, dtype=T.dtype).repeat(*T.shape[:-2], 1, 1),
        ],
        dim=-2,
    )
    return T_inv
